### ISSUE TITLE
vscodium in AUR does not build in a clean chroot

### ISSUE THREAD

**Issue by lahwaacz** [VSCodium/vscodium#1290]
Since the maintainer of the [vscodium](https://aur.archlinux.org/packages/vscodium) package does not respond to comments in the AUR and the PKGBUILD is now updated by [VSCodium CI](https://aur.archlinux.org/cgit/aur.git/commit/?h=vscodium&id=02076c86dd8a81ab31a9506f72168e2a370d59c2), I'll copy-paste the report here...

The package fails to build in a clean chroot due to a problem in the `version.sh` script. The build fails with:
```
...
==> Retrieving sources...
  -> Found vscodium.desktop
  -> Found vscodium-uri-handler.desktop
  -> Found VSCodium-1.72.1.22284-src.tar.gz
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting VSCodium-1.72.1.22284-src.tar.gz with bsdtar
==> Starting build()...
Downloading and installing node v16.14.2...
Downloading https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.xz...
######################################################################################################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.14.2 (npm v8.5.0)
Creating default alias: default -> v16.14.2
Found '/build/vscodium/src/.nvmrc' with version <v16.14.2>
Now using node v16.14.2 (npm v8.5.0)
RELEASE_VERSION="1.72.1.22284"
grep: warning: stray \ before /
grep: warning: stray \ before /
From https://github.com/Microsoft/vscode.git
MS_TAG="1.72.1"
MS_COMMIT="129500ee4c8ab7263461ffe327268ba56b9f210d"
From https://github.com/Microsoft/vscode
 * branch            129500ee4c8ab7263461ffe327268ba56b9f210d -> FETCH_HEAD
Note: switching to 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 129500e Merge pull request #485 from microsoft/dev/mjbvz/fix-command-id
fatal: not a git repository (or any of the parent directories): .git
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/lahwaacz/build
```

Original comment on the error: https://aur.archlinux.org/packages/vscodium#comment-884349

**Comment by daiyam** [comment]
@lahwaacz Thx for the ping. It should be fixed now.

**Comment by lahwaacz** [comment]
Thanks, it works for me now.

**Comment by TheOGUmar** [comment]
I still get an error on `v1.72.1.22284-2` using `yay -S vscodium`

```
:: (1/1) Parsing SRCINFO: vscodium
==> Making package: vscodium 1.72.1.22284-2 (Thursday 13 October 2022 10:07:09 AM)
==> Retrieving sources...
  -> Found vscodium.desktop
  -> Found vscodium-uri-handler.desktop
  -> Downloading VSCodium-1.72.1.22284-src.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 9014k  100 9014k    0     0   119k      0  0:01:15  0:01:15 --:--:--  308k
==> Validating source files with sha256sums...
    vscodium.desktop ... Passed
    vscodium-uri-handler.desktop ... Passed
    VSCodium-1.72.1.22284-src.tar.gz ... Passed
==> Making package: vscodium 1.72.1.22284-2 (Thursday 13 October 2022 10:08:26 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found vscodium.desktop
  -> Found vscodium-uri-handler.desktop
  -> Found VSCodium-1.72.1.22284-src.tar.gz
==> Validating source files with sha256sums...
    vscodium.desktop ... Passed
    vscodium-uri-handler.desktop ... Passed
    VSCodium-1.72.1.22284-src.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting VSCodium-1.72.1.22284-src.tar.gz with bsdtar
==> Sources are ready.
==> Making package: vscodium 1.72.1.22284-2 (Thursday 13 October 2022 10:08:30 AM)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: vscodium
```

**Comment by lahwaacz** [comment]
@TheOGUmar Since you are not building in a clean chroot, you may need to remove the old build directory (which probably still contains the git repo which is not used anymore).
