### ISSUE TITLE
VSCodium starts with wmclass set as `codium-url-handler`

### ISSUE THREAD

**Issue by hcsch** [VSCodium/vscodium#1414]
**Describe the bug**
VSCodium starts with its wmclass set to `codium-url-handler` (as observed with GNOME looking glass). Due to this, the VSCodium windows get the application title "VSCodium - URL Handler" in the GNOME top bar. Additionally, this also causes the windows not to be displayed under the default .desktop file icon in the dash, also preventing "Pin to Dash" when right-clicking the icon of the active windows in the dash. This is due to the windows being associated with the `codium-url-handler.desktop` file.

microsoft/vscode#129953 is the upstream issue for this, but it seem no progress is being made there. @dr-br mentioned in that issue, that this seems to be due to `codium-url-handler.desktop` being the desktop file referenced in the `desktopName` property of `app/package.json`, as opposed to the `codium.desktop` file.

**Please confirm that this problem is VSCodium-specific**
- [ ] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. `pkill codium` to kill all VSCodium windows
2. Open VSCode via either the VSCodium Shortcut provided by the `codium.desktop` file, the `codium` CLI, or the URL launcher with `vscode://file/<some-absolute-file-path>`
3. Observe the above mentioned behaviour

**Expected behavior**
wmclass of all VSCodium windows (regardless of the way they were started) is set to `codium`, so the windows can be correctly associated with the `codium.desktop` file.

**Screenshots**
<details>
<summary>Click to expand (screenshots always take up way to much visual space in GitHub)</summary>

![screenshot of application title in top bar](https://user-images.githubusercontent.com/34245439/219902136-0e6409f7-cf79-45e3-a013-803d0b26eb1d.png)
![screenshot of active window icon in dash with name shown](https://user-images.githubusercontent.com/34245439/219902137-91e75339-cfcf-4a16-a996-f19e3716ff1f.png)
![Screenshot of active window icon menu in dash missing "pin to dash"](https://user-images.githubusercontent.com/34245439/219902139-8d1e961d-054a-428c-a839-bcc485e22596.png)

</details>

**Desktop (please complete the following information):**
 - OS: NixOS (version 23.05.20230215.28319de; nixpkgs revision 28319deb5ab05458d9cd5c7d99e1a24ec2e8fc4b)
 - Architecture: x64
 - Version: 1.75.0
 - App Manager: Nix / home-manager
 - Sandboxed: no

**Comment by sambilbow** [comment]
I'm getting around this currently by creating a `codium-url-handler.desktop` file as per this [reply](https://github.com/microsoft/vscode/issues/129953#issuecomment-1315491384). Mine is customised a bit to run in electron for fractional scaling reasons:

```
[Desktop Entry]
Name=Codium
Comment=Code Editing. Refind.
GenericName=Text Editor
Exec=/usr/bin/codium --enable-features=UseOzonePlatform --ozone-platform=wayland --no-sandbox --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=False
StartupWMCClass=codium-url-handler
Categories=Utility;TextEditor;Development;IDE;
Actions=new-empty-window;

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/usr/bin/codium --no-sandbox --new-window %F
```

**Comment by hcsch** [comment]
While that should work to fix the window grouping issues, that probably also breaks the URL handler, sadly. Copying `codium.desktop` to `~/.local/share/applications/` and changing `StartupWMClass` to `codium-url-handler` should work as a temporary workaround though.

**Comment by bbhtt** [comment]
still an issue, I think

**Comment by zincentimeter** [comment]
I also observed this on vscode with wayland.

**Comment by vec715** [comment]
any updates? Still actual meh

**Comment by Luflosi** [comment]
This should be fixed in https://github.com/microsoft/vscode/pull/231472. I believe version 1.95.0 includes this fix.

**Comment by JotaRata** [comment]
I confirm the issue is still present in version 1.97.0 (Feb. 2025) installed through Discover running on Arch linux using KDE/Plasma 6.3 and Wayland.
Only fix I found was to go to Settings > Flatpak permisions > VSCodium and disable Wayland support

**Comment by quokkawiki** [comment]
This is still relavant on 1.100.13210!

**Comment by cos4ni2s** [comment]
Still an issue

**Comment by daiyam** [comment]
@hypevhs Is it still an issue?

For Aur, the issue has been fixed (on the repos which I maintain).
For Nix, I haven't tested and isn't maintained by me.
