### ISSUE TITLE
Cannot Open Jupyter Notebook in version 1.78.1

### ISSUE THREAD

**Issue by Romeo-CC** [VSCodium/vscodium#1508]
**Describe the bug**

When open a jupyter notebook (`.ipynb`) file using the latest version (`1.78.1`) of VScodium
the content of the notebook could not be rendered properly, both `code blocks` and `markdowns`
For more details please refer to the screenshots.

using vscode open the same notebook file, this bug does not happen.

**Please confirm that this problem is VSCodium-specific**
- [x] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium.

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
0. Install VScodium 1.78.1
1. Go to 'extensions' of vscodium
2. Install the latest version of the extensions as follow:
   + Jupyter Notebook Renderers 
   + Jupyter Slide Show 
   + Python 
   + Jupyter Cell Tags 
   + Jupyter Keymap 
3. open any notebook (`.ipynb`) file 

**Expected behavior**

1. Find out the reason why this bug occurs.
2. Fix it.
**Screenshots**

![vscodium_jupyter_bug](https://github.com/VSCodium/vscodium/assets/13418210/6eaae924-bdb4-48dd-a168-afdeeb490996)
this is the bug in vscodium
![2023-05-10_18-37](https://github.com/VSCodium/vscodium/assets/13418210/c9bcb9a7-48c4-4491-9b71-9a4fbc2fe39d)
this is expected normally, openning in with vscode 
**Desktop (please complete the following information):**
 - OS: Mac OS 13.3.1
 - Architecture x64
 - Version 1.78.1

**Additional context**

At first, I made a soft link file of vscode extentions to replace the extentions of vscode-oss, and I closed the plugins autoupdate of vscodium in order to letting vscode and vscodium share the extensions in vscode.
Everything works well when both vscode and vscodium are at the version of 1.77s.

After vscode upgraded to 1.78, the extensions updated to the latest as well. Today I updated my vscodium to the latest version(`1.78.1`) and I met the bug mentioned above.

I supposed this situation might be caused by the incompatibly of the extensions and vscodium. 
So I removed the soft link of vscode extensions and install the extensions (list as follow) in the vscodium plugins market:
+ Jupyter Notebook Renderers v1.0.15
+ Jupyter Slide Show v0.1.5
+ Python v2023.8.0
+ Jupyter Cell Tags v0.1.8
+ Jupyter Keymap v1.1.0

This bug still occurs.

**Comment by yv97** [comment]
+1
- OS: Windows 11 22H2
- Architecture: x64
- Version: 1.78.1

**Comment by tc2290** [comment]
+1
OS: Windows 10 Pro 22H2
Arch: x64
Version: 1.78.1

**Comment by PatrickAlyson** [comment]
+1

- OS : Ubuntu 22.04.2 LTS
- Architecture: x64
- Version: 1.78.1

**Comment by salym** [comment]
I have the same issue on MacOS M1 fully updated.

**Comment by art-r** [comment]
I have the same problem (opening jupyter notebooks, markdown previes, ...)
It seems like this is related to #1510 #1507 #1503 and #1502 

Version info:
```
Version: 1.78.1
Release: 23130
Commit: 748cf23d39091308b3b0d65ac43f0d784709fdcc
Date: 2023-05-10T01:14:55.248Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
```

Error code in debug tools:
```bash
index.html:16 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'sha256-N4YFn5ze5crjPqMK/opogKs7bSGWtf3lmjV/3LfbSOs=' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-gL9sMIYaOSpgU2r/kGAnB4ETLEykloodzKO0BgrHHPQ='), or a nonce ('nonce-...') is required to enable inline execution.
```

Screenshot of the network tab (when trying to open a jupyter notebook)
![grafik](https://github.com/VSCodium/vscodium/assets/75607997/e9afb211-bf8b-4f64-a930-8eeb9b93360c)


From a first glance (without any expertise) it seems to me as if the Content Security Policy has problems with the sha256 configuration, as the hashes do not match.
According to the error log this is the expected sha256:
```
sha256-gL9sMIYaOSpgU2r/kGAnB4ETLEykloodzKO0BgrHHPQ=
```

But according to the network tab this is the sha256 that is being returned in the index.html (also suggested by error log):
```
sha256-N4YFn5ze5crjPqMK/opogKs7bSGWtf3lmjV/3LfbSOs='
```

This behaviour and the hashes are however consistent when trying to open a markdown preview or different jupyter notebooks.
**However this is only what I found weird and it could totally not be the issue of this problem**

### Current workaround that works for me:
Downgrade to last version and everything works again

**Comment by Moini** [comment]
@art-r Thanks! I couldn't see any messages in my debug tools, but this sounds like a very likely cause. 

Hope @daiyam can let us know soon what has been going on.

**Comment by Romeo-CC** [comment]
this bug has beeb fixed in the latest release 23131

**Comment by y-voigt** [comment]
+1
Nothing changed for me either, VSCodium is still not displaying Markdown or Jupyter notebooks.

Version: 1.78.1 (system setup)
Release: 23131
Commit: abdfa343d7fcd6ee2fd896e746a586e990db1e33
Date: 2023-05-11T15:09:14.581Z
Electron: 22.3.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22624
Sandboxed: No

**Comment by daiyam** [comment]
I've made an update at #1515
