### ISSUE TITLE
Hung installing updates

### ISSUE THREAD

**Issue by SamHobbsOrg** [VSCodium/vscodium#1610]
Type: <b>Bug</b>

In the help menu I selected to install updates. The menu item remains "Installing update..." until I logoff. When I restart it says I need to do an update. I think in the relevant logs the `remoteTunnelService.log` file says:

`Missing 'tunnelApplicationConfig' or 'tunnelApplicationName' in product.json. Remote tunneling is not available.`

I assume that is not relevant. The `main.log` file says:

`2023-08-18 21:03:15.780 [info] update#setState checking for updates
2023-08-18 21:03:15.843 [info] update#setState downloading
2023-08-18 21:03:15.856 [info] update#setState downloaded
2023-08-18 21:03:41.241 [info] update#setState updating
2023-08-18 21:03:53.106 [info] Extension host with pid 12244 exited with code: 0, signal: unknown.`

There are messages in `main.log` about ssh and WSL that I assume are not relevant.

I had two extensions installed and I uninstalled both of them and the problem still exists.

VSCodium version: VSCodium 1.81.0 (ee0ba35e0f5ffb18669618446b41de0e99569167, 2023-08-04T14:24:43.542Z)
OS version: Windows_NT x64 10.0.22631
Modes: Restricted

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900 (24 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (5.42GB free)|
|Process Argv|--enable-proposed-api jeanp413.open-remote-ssh|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by camheelio** [comment]
I have the same problem since 1.80. 
The reason seems to be, that the correct package is downloaded as 
`%TEMP%\codium-stable-undefined-x64\CodeSetup-stable-....exe"` 
but Windows denies to execute it, since it is in fact an msi package. Renaming the file to *.msi makes it possible to run the downloaded installer manually. The strange thing: I have 4 identical system setups and only on one of them this happens. All others auto-update fine. All are system-installations of VSCodium.

**Comment by SamHobbsOrg** [comment]
I do not know how I fixed it. I think I uninstalled VSCodium and reinstalled.

**Comment by daiyam** [comment]
The *Type* is detected with the following code:
```
function getUpdateType(): UpdateType {
	if (typeof _updateType === 'undefined') {
		if (fs.existsSync(path.join(path.dirname(process.execPath), 'unins000.exe'))) {
			_updateType = UpdateType.Setup;
		} else if (path.basename(path.normalize(path.join(process.execPath, '..', '..'))) === 'Program Files') {
			_updateType = UpdateType.WindowsInstaller;
		} else {
			_updateType = UpdateType.Archive;
		}
	}

	return _updateType;
}
```

**Comment by quixoticaxis** [comment]
The issue still persists. On Windows 11 the downloaded file has .exe extension and isnot runnable unless renamed to .msi.

**Comment by d-roduit** [comment]
I experience the same problem, I'm also on Windows 11.

I already had the problem several versions of VSCodium ago. To resolve the problem, I had to manually install the new version of VSCodium, then the following updates could be made through VSCodium.

Now it stopped working again. I am on version 1.89.1.24130 and I cannot install version 1.90.2.24171 through VSCodium.
