### ISSUE TITLE
Extension ms-python.python has stopped working in version 1.104 of VSCodium

### ISSUE THREAD

**Issue by MiltiadisKoutsokeras** [VSCodium/vscodium#2530]
The extension `ms-python.python` is no longer working in VSCodium, I have tested the following versions:

- 2025.14.0
- 2025.12.0
- 2025.4.0
- 2025.2.0

It is possible that the break is on many other versions. The error logs from the Extension Host is the following on activation:

```
2025-10-01 10:45:15.570 [error] [ms-python.python] provider FAILED
2025-10-01 10:45:15.570 [error] Error: ValueError: not enough values to unpack (expected 1, got 0)
	at ae (/home/username/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2016851)
	at oe (/home/username/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2014811)
	at Immediate.<anonymous> (/home/username/.vscode-oss/extensions/ms-python.python-2025.14.0-universal/out/client/extension.js:2:2011105)
	at process.processImmediate (node:internal/timers:485:21)
```

VsCodium version info:
```
Version: 1.104.26450
Commit: df23b135987b9b1449efdfb550fe90f38539b749
Date: 2025-09-25T18:34:07.817Z
Electron: 37.3.1
ElectronBuildId: undefined
Chromium: 138.0.7204.235
Node.js: 22.18.0
V8: 13.8.258.31-electron.0
OS: Linux x64 5.10.0-35-amd64
```

**Comment by MiltiadisKoutsokeras** [comment]
**UPDATE**: The Extension is fixed in version `2025.16.0` and Codium version:

```
Version: 1.105.17075
Commit: 14bd1561ce547502e6ff1968090dc18c49160aab
Date: 2025-10-21T20:24:03.344Z
Electron: 37.6.0
ElectronBuildId: undefined
Chromium: 138.0.7204.251
Node.js: 22.19.0
V8: 13.8.258.32-electron.0
OS: Linux x64 5.10.0-36-amd64
```

**Comment by omnicortex** [comment]
> **UPDATE**: The Extension is fixed in version `2025.16.0` and Codium version:
> 
> ```
> Version: 1.105.17075
> Commit: 14bd1561ce547502e6ff1968090dc18c49160aab
> Date: 2025-10-21T20:24:03.344Z
> Electron: 37.6.0
> ElectronBuildId: undefined
> Chromium: 138.0.7204.251
> Node.js: 22.19.0
> V8: 13.8.258.32-electron.0
> OS: Linux x64 5.10.0-36-amd64
> ```

I am still having this error with these same versions. I am on Mint 22
