### ISSUE TITLE
Wrong version number for version 1.43.0

### ISSUE THREAD

**Issue by audpa33** [VSCodium/vscodium#362]
**Describe the bug**
VSCodium  version 1.43.0 (VSCodium-win32-x64-1.43.0.zip) has a version number 1.44.0.
VSCodium reports an available update and propose to download version 1.43.0.

**Expected behavior**
Version should be 1.43.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Architecture x64
 - Version 1.43.0

**Please confirm that this problem is VSCodium-specific**
Not checked. 

**To Reproduce**
1. Go to Help
2. Click on About
3. Version is 1.44.0

**Comment by kogiokka** [comment]
This bug also make VSCodium keep showing "Download Update" notification.

**Comment by kogiokka** [comment]
This bug should be fixed after downloading the latest release once again. The version numbers in "About" and Release Notes will be back to 1.43.0.

**Comment by audpa33** [comment]
Many thanks for the fix. :-)

**Comment by renestalder** [comment]
@audpa33 @kogiokka Does that also apply to the package repositories like in Ubuntu? Or what's the solution when VSCodium was installed from those repositories?

As the repository still shows me that 1.44.0 is the latest version

**Comment by kogiokka** [comment]
@renestalder I use `tar.gz` version from the [release page](https://github.com/VSCodium/vscodium/releases), so I assume this issue has been fixed as long as the package is from there. Not sure about [vscodium-deb-rpm-repo](https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo) though.
