### ISSUE TITLE
Git extension is super slow since version 1.56.0

### ISSUE THREAD

**Issue by mlbiche** [VSCodium/vscodium#718]
**Describe the bug**

Since VSCodium updated to 1.56.0, I am suffering important slowdown of the editor. The SCM is particularly slow in all its features (especially showing diffs and refreshing changes, but also committing). It also causes slowdown for the GitLens extension but the slowdown remain even when disabling the extension. I have run an extension audit and it has shown that Git extension was some time not responsive. It causes slowdown in the whole application, with a kind of side effect on other extensions such as ESLint or Prettier.

I have downgraded VSCodium to the version 1.55.2 and everything is running smoothly then. Upgrading back to 1.56 show the slowdown again?

**Please confirm that this problem is VSCodium-specific**
- [X] This bug doesn't happen if I use Microsoft's Visual Studio Code. It only happens in VSCodium. I have tried it on the same project with Visual Studio Code 1.56.

**Please confirm that the issue/resolution isn't already documented**
- [X] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Open a project with a remote
2. Write down some edits.
3. Open the SCM tab. It should be loading for while
4. Click a changed file, the diff should takes a while to show up.

**Expected behavior**
A SCM as fas as it as in the version 1.55.2.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Architecture x64
 - Version 1.56.0

**Comment by paulcarroty** [comment]
Can't reproduce it on Linux.

**Comment by Nopraz** [comment]
@daiyam If it is the extension that does this problem do we have the same problem on Visual Studio Code and not only Vscodium ?

**Comment by daiyam** [comment]
@Nopraz Good question. Can you check if you are getting the errors on VSCode even if it's not slow?

**Comment by Nopraz** [comment]
Just checked, no errors on visual studio code

**Comment by mlbiche** [comment]
I have also checked on VSCode the other day and have not seen any slowdown.

**Comment by daiyam** [comment]
I can't reproduce the error with VSCodium v1.56.1 and the examples from the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/).
Can you give me example of the files on which you are getting the errors? Or try those examples?

**Comment by robinloeffel** [comment]
It's slowed down everywhere—even when just opening up a tiny project I'll see "Initializing JS/TS language features..." and "Activating language features..." spinning in my status bar for what feels like 5 seconds each. It's gotten significantly better for me with v1.56.2, but it's still not where v1.55.2 was. I notice it most when Git pulling (via the UI) and when the autofix feature enabled via `editor.codeActionsOnSave.source.fixAll` is working.

**Comment by MrOggy85** [comment]
I have the same issue:
MacBook Pro
MacOs Big Sur, 11.3
```sh
$ uname -a
Darwin (HOSTNAME) 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:14 PST 2021; root:xnu-7195.101.1~3/RELEASE_X86_64 x86_64
```

I just downloaded and installed `1.55.2` and the issue is gone

**Comment by sagolubev** [comment]
I faced the same issue:
Mb Pro 2018, Big Sur 11.3.1
`$ uname -a
Darwin (HOSTNAME) 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64`
Git:
`$ git --version`
`git version 2.31.1`

**Comment by daiyam** [comment]
@mlbiche @MrOggy85 @sagolubev Can you troubleshoot your setup? I'm on macOS and I can't reproduce the issue. I've opened vscode project with gitlens activated and I don't any slow down.
Can you try a blank VSCodium with just gitlens activated?

Does the solution of @robinloeffel is working?

```
{
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  }
}
```

**Comment by MrOggy85** [comment]
@daiyam I tried it, but no difference. 
I have `Gitlens` extension installed but I also tried to disabled it but no difference.
I also disabled all extensions, but no difference.
I also removed all my settings, but no difference.

It happens for any type of files. I have tried with `.ts`, `.json`, `.md` 
It happens both if I open a folder and if I use workspace (which is even slower).

**Comment by daiyam** [comment]
Can you edit `/Applications/VSCodium.app/Contents/Resources/app/product.json` and replace `"extensionAllowedProposedApi": [...],` with the following code?

```
"extensionAllowedProposedApi": ["GitHub.codespaces", "GitHub.vscode-pull-request-github-insiders", "GitHub.vscode-pull-request-github", "Microsoft.vscode-nmake-tools", "ms-ai-tools.notebook-renderers", "ms-dotnettools.dotnet-interactive-vscode", "ms-python.gather", "ms-python.python", "ms-toolsai.jupyter", "ms-toolsai.vscode-ai", "ms-toolsai.vscode-ai-remote", "ms-vscode-remote.remote-containers-nightly", "ms-vscode-remote.remote-containers", "ms-vscode-remote.remote-ssh-edit-nightly", "ms-vscode-remote.remote-ssh-edit", "ms-vscode-remote.remote-ssh-nightly", "ms-vscode-remote.remote-ssh", "ms-vscode-remote.remote-wsl-nightly", "ms-vscode-remote.remote-wsl", "ms-vscode-remote.remote-wsl-recommender", "ms-vscode-remote.vscode-remote-extensionpack-nightly", "ms-vscode-remote.vscode-remote-extensionpack", "ms-vscode.azure-account", "ms-vscode.azure-sphere-tools-ui", "ms-vscode.azure-sphere-tools", "ms-vscode.github-browser", "ms-vscode.github-richnav", "ms-vscode.remotehub", "ms-vscode.remotehub-insiders", "ms-vscode.js-debug-nightly", "ms-vscode.js-debug", "ms-vscode.lsif-browser", "ms-vscode.vscode-js-profile-flame", "ms-vscode.vscode-js-profile-table", "ms-vscode.vscode-selfhost-test-provider", "ms-vscode.test-adapter-converter", "ms-vsliveshare.cloudenv-explorer", "ms-vsliveshare.cloudenv", "ms-vsliveshare.vsliveshare", "ms-vsonline.vsonline", "dbaeumer.vscode-eslint"],
```

**Comment by MrOggy85** [comment]
I also tried removing the app and install the latest version from the .dmg file from "Releases" page here on Github.
But, still same issue.

Originally I installed vscodium from `brew`, if that helps at all.

**Comment by daiyam** [comment]
I've looked at the git extension and I've seen that vscode's team have added virtual workspaces. So the change of `extensionAllowedProposedApi ` was related to that. Maybe it's another property of `product.json` that needs to be updated, but I don't know...

**Comment by d11-acummins** [comment]
This still occurs on latest. Also tried disabling all extensions, but no luck

- OS: macOS 11.2.3
- Architecture x64
- Version 1.57.1

**Comment by MrAlexWeber** [comment]
I was able to confirm that downgrading to 1.55.2 fixed my issue with laggy editor behavior when switching tabs or opening files.

**Comment by daiyam** [comment]
Was it from local files or remote files?

**Comment by stripedpajamas** [comment]
I was also able to reproduce this issue on my mac with versions >1.55.2. The whole editor became noticibly sluggish. I'll keep poking at it to see if I can figure out what changed.

**Comment by daiyam** [comment]
While playing with remote ssh, I found that I can't connect to my VM with VSCodium where I can with VSCode...

**Comment by MrAlexWeber** [comment]
For me, local files.

**Comment by atapfedora** [comment]
Same here in Manjaro, I tried to install python extension on Vscodium, but it keeps "installing" and nothing happens

**Comment by enx1998** [comment]
Hi,
I have the same problem with 1.57.1 version and macos 11.4 on a macbook pro 16".
I add that the extension doesn't work (it doesn't recognize the git repository) until I disable and enable it again.

**Comment by daiyam** [comment]
@atapfedora @enx1998 If you are talking about the python extension, please open another issue. This issue is about slow git...

**Comment by daiyam** [comment]
For the git issue, I can't reproduce it on my macOS or my arch linux... VSCode is having the same issue (for example: https://github.com/microsoft/vscode/issues/120883)

Can you share your `git --version` and the `Git` log in `View/Output`?

**Comment by MrAlexWeber** [comment]
`git --version` returns `git version 2.32.0`.

I reverted to 1.55.x so I can't get the output log right now.

**Comment by enx1998** [comment]
@daiyam `git --version` return `git version 2.30.1 (Apple Git-130)`.  
In `Git` log I can't see anything strange, only these messages repeating for each change (I think) I made to project files:
```
> git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
> git remote --verbose
> git config --get commit.template
> git show --textconv :resources/assets/js/main/login.js
> git ls-files --stage -- resources/assets/js/main/login.js
> git check-ignore -v -z --stdin
> git cat-file -s 341e36b9b819ada3dcf91969960bd2fc34f2f665
> git status -z -u
> git symbolic-ref --short HEAD
> git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/feature/newsletter_registration_flag refs/remotes/feature/
```

For the extension that doesn't work, I mean the native Git extension.

**Comment by enx1998** [comment]
@daiyam I can add that with version 1.57.1 a project take 23 seconds to load with all extensions, instead with 1.55.2 the same project loads in 4 seconds.
In 1.57.1 I can see these messages on output window log:
```
[2021-07-11 00:33:14.049] [renderer1] [warning] [File Watcher (chokidar)] Watcher is not using native fsevents library and is falling back to unefficient polling.
[2021-07-11 00:33:14.244] [renderer1] [error] Cannot delete property '0' of [object String]: TypeError: Cannot delete property '0' of [object String]
    at s (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:15207)
    at o (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:14258)
    at n._handler (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:14837)
    at n._handle (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:5401)
    at n.acceptUsers (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:5305)
    at Function._handleExtensionPoint (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:121627)
    at Va._doHandleExtensionPoints (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:120746)
    at Va._startLocalExtensionHost (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2944:9392)
    at async Va._scanAndHandleExtensions (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2944:8354)
    at async Va._initialize (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:115281)
[2021-07-11 00:33:14.266] [renderer1] [error] Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at Object.D [as equalsIgnoreCase] (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:62319)
    at file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1811:43224
    at Array.find (<anonymous>)
    at d.getDebugger (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1811:43214)
    at file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39968
    at Array.forEach (<anonymous>)
    at file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39852
    at Array.forEach (<anonymous>)
    at n._handler (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1811:39832)
    at n._handle (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:5401)
    at n.acceptUsers (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1809:5305)
    at Function._handleExtensionPoint (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:121627)
    at Va._doHandleExtensionPoints (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:120746)
    at Va._startLocalExtensionHost (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2944:9392)
    at async Va._scanAndHandleExtensions (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2944:8354)
    at async Va._initialize (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:115281)
[2021-07-11 00:33:26.443] [renderer1] [warning] UNRESPONSIVE extension host, 'amiralizadeh9480.laravel-extra-intellisense' took 99% of 1846.49ms, saved PROFILE here: 'file:///var/folders/wp/fjgmfqm9615b4x4m8106m9sc0000gn/T/exthost-ceeb95.cpuprofile' [{"id":"amiralizadeh9480.laravel-extra-intellisense","total":1830609,"percentage":99},{"id":"bmewburn.vscode-intelephense-client","total":2571,"percentage":0},{"id":"codingyu.laravel-goto-view","total":115,"percentage":0},{"id":"ms-vscode.vscode-typescript-tslint-plugin","total":1186,"percentage":0},{"id":"neilbrayfield.php-docblocker","total":257,"percentage":0},{"id":"redhat.vscode-yaml","total":3480,"percentage":0},{"id":"self","total":6398,"percentage":0},{"id":"vscode.git","total":947,"percentage":0},{"id":"vscode.typescript-language-features","total":546,"percentage":0}]
[2021-07-11 00:33:44.755] [renderer1] [warning] UNRESPONSIVE extension host, 'redhat.vscode-yaml' took 84% of 15165.477ms, saved PROFILE here: 'file:///var/folders/wp/fjgmfqm9615b4x4m8106m9sc0000gn/T/exthost-a58d85.cpuprofile' [{"id":"bmewburn.vscode-intelephense-client","total":1095300,"percentage":7},{"id":"gc","total":11412,"percentage":0},{"id":"program","total":1156,"percentage":0},{"id":"redhat.vscode-yaml","total":12773258,"percentage":84},{"id":"self","total":2813,"percentage":0},{"id":"TabNine.tabnine-vscode","total":773579,"percentage":5},{"id":"vscode.json-language-features","total":506585,"percentage":3},{"id":"vscode.npm","total":888,"percentage":0},{"id":"vscode.php-language-features","total":133,"percentage":0}]
[2021-07-11 00:33:48.395] [renderer1] [error] Unable to write to User Settings because tabnine.experimentalAutoImports is not a registered configuration.: Error: Unable to write to User Settings because tabnine.experimentalAutoImports is not a registered configuration.
    at S.reject (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:15315)
    at S.resolveAndValidate (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:18300)
    at S.doWriteConfiguration (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:12505)
    at Object.factory (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:12281)
    at E.consume (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:68:16017)
    at file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:68:15832
    at new Promise (<anonymous>)
    at E.queue (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:68:15756)
    at S.writeConfiguration (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:12266)
    at E.writeConfigurationValue (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:41473)
    at file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:27566
    at Array.map (<anonymous>)
    at E.updateValue (file:///Applications/Developer/VSCodium.new.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2409:27554)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2021-07-11 00:33:49.010] [renderer1] [error] Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at Object.GetDefaultLevel (/Users/enx/.vscode-oss/extensions/bobmagicii.autofoldyeah-1.0.6/extension.js:287:37)
    at Object.GetLevel (/Users/enx/.vscode-oss/extensions/bobmagicii.autofoldyeah-1.0.6/extension.js:262:27)
    at Object.Fold (/Users/enx/.vscode-oss/extensions/bobmagicii.autofoldyeah-1.0.6/extension.js:96:31)
    at Timeout._onTimeout (/Users/enx/.vscode-oss/extensions/bobmagicii.autofoldyeah-1.0.6/extension.js:187:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    ```
that don't appear in 1.55.2 version.

**Comment by daiyam** [comment]
@enx1998 There were a problem with the extensions https://github.com/microsoft/vscode/issues/125989 which is been fixed in `v1.58.0`. It was only for VSCode not for VSCodium. 
PS: you've posted the console log not the `View/Output/Git channel`...

**Comment by MrAlexWeber** [comment]
My VSCodium updated to 1.57.1 so I can reproduce the issue again.

When switching between files, the git log looks like:
```
> git show --textconv :src/sagas/sip.ts
> git ls-files --stage -- /path/to/sip.ts
> git cat-file -s 4a863852c355f1037422e48b744c9f77ea171aad
> git show --textconv :src/sagas/app.ts
> git ls-files --stage -- /path/to/app.ts
> git cat-file -s a98f892e02de07cef382b196cb4f026d61c38c74
> git show --textconv :src/sagas/sip.ts
> git ls-files --stage -- /path/to/sip.ts
> git cat-file -s 4a863852c355f1037422e48b744c9f77ea171aad
```
When switching between two open editor tabs, I notice a delay of about 2s before the cursor starts moving.

I'm still seeing `git version 2.32.0` and `which git` returns `/usr/local/Homebrew/bin/git`

**Comment by MrAlexWeber** [comment]
I just updated to 1.58.0 and the issue is still present on that version as well. Thanks for looking into this!

**Comment by daiyam** [comment]
@MrAlexWeber I don't see nothing unusual... 

Do you activities in `Help/Open Process Explorer` when switching tabs?
Do you have the same problem when the files aren't in a git tracked folder?

**Comment by MrAlexWeber** [comment]
> Do you activities in `Help/Open Process Explorer` when switching tabs?

When switching tabs I see spikes on `extensionHost` and `watcherService` but not much besides that. Sometimes I see brief spikes of activity for `electron_node eslintServer.js`. 

I disabled ESLint and Prettier, but was still able to reproduce the issue with the unresponsive editor. The Git extension shows "⚠️ Unresponsive".

> Do you have the same problem when the files aren't in a git tracked folder?

I tried to reproduce it using some plain text files and did not see the same amount of lag. Where usually I see 2-3 seconds of lag in a folder with git enabled when switching to a file, testing in a non-git directory only showed a fraction of a second of lag.

**Comment by daiyam** [comment]
Hi, I found this: https://github.com/microsoft/vscode/issues/107103#issuecomment-749901444 Can you try?
For VSCodium, it should be:
```
codesign --remove-signature "/Applications/VSCodium.app/Contents/Frameworks/VSCodium Helper (Renderer).app"
```
or 
```
codesign --remove-signature "/Applications/VSCodium.app/Contents/Frameworks/*.app"
```

Don't forget to restart VSCodium before testing both commands. Thx

**Comment by mlbiche** [comment]
Just tried both, even trying to remove signatures from each app within the Frameworks folder and version 1.59 is still super laggy compared to 1.55. I even tried completely removing VSCodium and reinstalling it but it doesn't fix the issue...

From issues on VSCode repo, I read that it might be related to Electron, Node.js or MacOS kernel and not the app itself, so you guys might not be able to fix it. 😞 

What is strange is that I do not have the slowness with latest VSCode version...

**Comment by mp3foley** [comment]
I find this is most noticeable with the vscodevim extension.  It makes keystrokes lag for the first few seconds after switching tabs.  I have purposefully been running 1.55 for many months because of this.  Today I upgraded to 1.59.1 using brew.  This is still an issue.

I tested on a folder that was not a git repository and did not notice the same lag.  I also tested by disabling the git extension with: `"git.enabled": false,`
and that also helped.  I will run without the git extension for now, as I mostly use other Git tools, but this will not be a solution for most users, and I am considering switching back to normal VSCode.

I am running MacOS BigSur 11.5.2, and tested with VSCodium:
Version: 1.59.1
Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa

Let me know if I can assist with any other information or testing.

**Comment by senfbrot** [comment]
I can confirm @mp3foley's finding. Retested with 1.59.1 (installed/updated with brew) and the git integration is still horrible slow. I'm going back to 1.55 again.

Tested on MacBook Pro 2019 with MacOS BigSur 11.4

**Comment by RomainFallet** [comment]
Same with version 1.60 on mac OS Big Sur 11.5.2, any news on this?

**Comment by VoidAndAny** [comment]
Thanks for the tip (rollback to 1.55), since my Big Sur update VSCodium was almost unusable (git)

**Comment by vic-pic** [comment]
Hi everyone,
there is some progress to this issue?

Thanks ENx

**Comment by Nesh108** [comment]
@VoidAndAny How did you manage to rollback with brew?

**Comment by Buzut** [comment]
Hey all, I had faced the issue too and wanted to give it a new try. Tried varying versions yesterday ranging from the latest 60.2 to 1.55.2 and everything up from 1.55.2 is laggy. Git and GitLens are unusable. 
I tried to run VS with all extensions disabled, but no luck. Back to 1.55.2 and it works like a charm. I really hope there's a solution coming or we're all stuck with an old version.

MacBook Pro 2018
macOS 11.6
name -a:  20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

**Comment by TyMick** [comment]
Huh, I didn't realize it was a Mac-only issue. For the record, though, VS Code itself has been working completely fine for me on Mac since VSCodium broke. I just checked again, and I'm still experiencing the same unreasonable git extension slowness in VSCodium but not in VS Code. Same version, same commit hash, everything.

<img width="266" alt="Screen Shot 2021-10-30 at 8 08 36 AM" src="https://user-images.githubusercontent.com/5317080/139540388-bfb76337-4d25-4193-9b85-61a6cad7b300.png"> <img width="266" alt="Screen Shot 2021-10-30 at 8 08 18 AM" src="https://user-images.githubusercontent.com/5317080/139540382-7b38db1a-3549-4ddf-a681-ba1ea8445b23.png">

Baffling. I tried looking at the diffs between 1.55.2 and 1.56.0 [in VSCodium](https://github.com/VSCodium/vscodium/compare/1.55.2..1.56.0) and [in VS Code](https://github.com/microsoft/vscode/compare/1.55.2..1.56.0) for a bit, but nothing's jumping out at me. I might try building VS Code from source, following [Microsoft's instructions](https://github.com/microsoft/vscode/wiki/How-to-Contribute#build-and-run), sometime to see if VSCodium's issues exist then, and if not, compare those instructions to VSCodium's build scripts.

I'd really love to get back to using VSCodium, but... I've gotta get work done.

**Comment by mlbiche** [comment]
It's getting even more problematic for me today as our team moved to major updates of our project dependencies and some of my VSX Extensions then require updates not compatible with VSCodium 1.55. I am turning off the Git extension for now, but it feels like uncomfortable.

I tried again to run `codesign --remove-signature ...` but it is ineffective.

**Comment by Nesh108** [comment]
Yeah, it's truly annoying, VSCodium updates to the latest version even though I said not to...

So I have make sure not to close the application or I need to replace the executable every time. 

Can anyone expert in the codebase point to where the issue comes from? We are a bunch of developers we might figure out how to fix it..

**Comment by Nesh108** [comment]
So something here caused the issue: https://github.com/VSCodium/vscodium/compare/1.55.2..1.56.0

Since its just a patch file for the gallery, couldn't we try to revert it and rebuild the latest version to see if that fixes it?

**Comment by mlbiche** [comment]
@Nesh108 The issue may be caused by VSCode code. I found some GitHub issues on VSCode repository mentioning slowness related to the Git extension

**Comment by Nesh108** [comment]
Then we should look at this: https://github.com/microsoft/vscode/compare/1.55.2..1.56.0

**Comment by dandavison** [comment]
I tried to look into this a bit. I don't have a solution but in case it's helpful here are some notes. cc @lszomoru @joaomoreno in case you'd be kind enough to explain this performance problem we're seeing with the git extension in OSS builds since 1.55.2 (but not in Microsoft's build on the same git tag `1.64.0`).

- When I save a file that's in a git repo in vscode, for a second or two afterwards cursor movement is obviously impeded (e.g. if you hold the down arrow it "freezes" momentarily). During this time, vscode starts various external git processes:

**1.64.0**
```
24ms: git status -z -u
18ms: git symbolic-ref --short HEAD
24ms: git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track) refs/heads/master refs/remotes/master
296ms: git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
19ms: git remote --verbose
17ms: git config --get commit.template
```

- Notice the slow `git for-each-ref` call. Those timings are on a recent vscode commit (git tag `1.64.0`). But using `1.55.2` that `for-each-ref` call is much faster, and cursor movement is unaffected:

**1.55.2**
```
23ms: git status -z -u
18ms: git symbolic-ref --short HEAD
23ms: git for-each-ref --format=%(refname)%00%(upstream:short)%00%(upstream:track)%00%(objectname) refs/heads/master refs/remotes/master
21ms: git remote --verbose
42ms: git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname)
22ms: git config --get commit.template
```

- So the command line arguments passed to git, and the state of the git repository, are identical, but the `git for-each-ref` process is taking ~6x longer to complete under 1.64. (On `master` (1.65) it's ~10x longer). I used `dtruss` to confirm that exactly the same sequence of sys calls are made by the two git processes.

- I assume this unexplained timing difference is related to the cursor movement UI performance problem that is the real issue here.

-  My personal guess is that what's happening is that vscode 1.64 is being much slower than 1.55.2 in reading the data from the child git process; i.e. the child process is getting blocked in writing to the pipe because the buffer is filling up.

- One thing I'm a bit surprised by is that activity in the `extensions/git/` part of vscode affects the performance of UI rendering: my understanding was that the multi-process architecture of vscode was designed to prevent that.

- Setting `"git.autorefresh": false` improves things -- vscode doesn't make the external git calls on file save.

- To obtain the timings above I created a shell wrapper for git to record the calls vscode is making (perhaps I could have used logging built into vscode):
```sh
#!/bin/bash
GIT=/PATH/TO/REAL/git
start_ms=$(date '+%s%3N')
$GIT "$@"
status=$?
end_ms=$(date '+%s%3N')
ms=$((end_ms - start_ms))
cmd="$(basename $0) $*"
echo "${ms}ms: $cmd" >>/tmp/git.log
exit $status
```

**Comment by daiyam** [comment]
@dandavison If you run those commands by hand (in the same order), do you get the same result?

**Comment by dandavison** [comment]
If I run them by hand I get the fast timing. I only see the slow timing when the git process is a child process of a vscode OSS build.

> those 296ms is just how much time the process ran (without vscode's parsing).

In order for the line `$GIT "$@"` to complete, the output of the git command must be written somewhere. And when the shell wrapper is invoked by vscode, the "somewhere" is a pipe connecting the shell process to vscode. And if that pipe gets full, then the shell process will be temporarily unable to write. The end result will be that the line `$GIT "$@"` will take longer to complete when run under vscode than when run by hand -- if vscode is doing a bad job of reading from the pipe.

**Comment by pieterdt** [comment]
That was the case for me indeed, and I'm following this issue for a while because I have the same problem.

**Comment by Nesh108** [comment]
@robrecord My vscodium terminal (`v1.55.2`), this is the version of git used `2.30.1 (Apple Git-130)` (output of `git --version`). My system version is: `2.20.1`.

The git version used on `v1.64.2 ` is also `2.30.1 (Apple Git-130)`

**Comment by robrecord** [comment]
Another thing that is possibly related is that I get very slow project-wide searches on VSCodium. Just switched back to VSCode and it's fast again. So it might be related to filesystem operations.

**Comment by Nesh108** [comment]
How does `git status` connect to the filesystem deep down? Maybe that's the issue?

**Comment by dandavison** [comment]
> Can I just check, did you - as I did - use the method of migrating to VSCodium that involves copying or linking wholesale the settings/extensions of VSCode into VSCodium's directories?

Hi @robrecord, I'm not actually using VSCodium -- the git extension performance problems I described are from (on MacOS) building VSCode from the repo with `yarn gulp vscode-darwin-x64`.

**Comment by Nesh108** [comment]
Any update on the issue? I'd love to update sooner or later 😅

**Comment by brkn** [comment]
I'm on version
```
1.65.1
8908a9ca0f221f36507231afb39d2d8d1e182702
x64
```

Git and file speed is back to normal for me.

**Comment by eloo** [comment]
for me its still super slow :(

```
[2022-03-28T13:26:54.297Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [806ms]
[2022-03-28T13:26:56.684Z] > git ls-files --stage -- /Users/... [1182ms]
[2022-03-28T13:26:57.077Z] > git config --get commit.template [1976ms]
[2022-03-28T13:26:57.479Z] > git cat-file -s ... [402ms]
```

```
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0
```

and since it looks like nobody is trying to fix this i will switch back to vscode...

**Comment by robrecord** [comment]
> [2022-03-28T13:26:57.479Z] > git cat-file -s ... [402ms]

Do you mind telling us how you get these benchmark reports?

**Comment by dandavison** [comment]
Note that this doesn't seem to be a VSCodium problem -- it seems to be a problem with open source builds of VSCode in general (see my notes above: https://github.com/VSCodium/vscodium/issues/718#issuecomment-1030873490). So that's good in a way, because the problem is relevant to a much larger set of people and we can seek advice/explanation from anyone familiar with building VSCode; we should probably open an issue on the main VSCode repo (although we should check it's still occurring with the latest release).

**Comment by dandavison** [comment]
@robrecord can you characterize the git repo you're testing in -- many files? many branches/tags? etc I was testing in a very large monorepo with many branches and tags.

**Comment by robrecord** [comment]
> @robrecord can you characterize the git repo you're testing in -- many files? many branches/tags? etc I was testing in a very large monorepo with many branches and tags.

4 local branches, 3 remote branches, one remote, no tags, about a hundred commits.

**Comment by gabjauf** [comment]
Hey guys,

The observations I made on my side:
- **VSCodium has the issue**, not VSCode

- I get **100% CPU usage** process by Electron times the number of windows of VSCodium opened

- Stopping the "Electron" process causes the vscode.git extension to crash

- On startup, it takes a **lot of time to load because of vscode.git** (UNRESPONSIVE)

- During normal usage, **git extension is slow**, whatever is the repository I use

- It is happening on **Mac**, not linux (according to the comments)

My configuration:
```
Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-11T00:39:29.134Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0
```

Useful comments:
"I assume this unexplained timing difference is related to the cursor movement UI performance problem that is the real issue here" https://github.com/VSCodium/vscodium/issues/718#issuecomment-1030873490

@dandavison You said that "it seems to be a problem with open source builds of VSCode in general", do you have any issue referencing the same kind of issue in other open source builds of VSCode?

**Comment by dandavison** [comment]
> @dandavison You said that "it seems to be a problem with open source builds of VSCode in general", do you have any issue referencing the same kind of issue in other open source builds of VSCode?

Yes - the problems with the git extension performance that I reported above, and the timings, none of it used VSCodium in any way (in fact I've never used VSCodium). Everything I did was using OSS builds of vanilla VSCode on MacOS.

**Comment by daiyam** [comment]
> * **VSCodium has the issue**, not VSCode

To be clear, even some users of VSCode have the same issue.

**Comment by mlbiche** [comment]
Some issues on VSCode repository :
* https://github.com/microsoft/vscode/issues/134921
* https://github.com/microsoft/vscode/issues/123935

**Comment by angwe** [comment]
Cropping back up on my macOS Monterey machine with VSCodium 1.66.2

Recent happening too, it wasn't occurring with earlier version.

Most noticeable in the intersection between completion plug-ins (which suddenly hang and stall the cursor) and built-in git. Sometimes GitLens is trying to do something, but most of the time, it's just the background git process checking for updates.

**Comment by robrecord** [comment]
The only thing I can think of is that it's something to do with the compiler used.

**Comment by gabjauf** [comment]
<img width="554" alt="Capture d’écran 2022-04-22 à 10 06 01" src="https://user-images.githubusercontent.com/17923230/164645503-e6823cbc-5bb3-42bf-8b28-260bf77419cc.png">
[profile.json.zip](https://github.com/VSCodium/vscodium/files/8538714/profile.json.zip)
Found a CPU profile in the developer tools, if it can help 😉

**Comment by daiyam** [comment]
Hi, for those on M1, you might want to try the new arm64 binary.

**Comment by TheOnlyDasBoot** [comment]
Visual Studio 2019 v16.11.12 - If I am attached to the internet GitHub turns my pc into a turtle.  Disconnect internet and pc is the hare.  GitHub is a pig and has slowed down my ability to develop.  I am now informing management that using GitHub was a mistake where an investment into MS TFS would be much better.

**Comment by Nesh108** [comment]
@TheOnlyDasBoot here we are discussing how to fix a slowdown on VsCodium, not whining about GitHub. Make a new issue on https://github.com/github

**Comment by daiyam** [comment]
@TheOnlyDasBoot Your issue isn't related to VSCodium so please avoid any further ranting here. Thx

**Comment by mlbiche** [comment]
I have updated VSCodium to version 1.67.0 and tried to enable the Git extension again and it seems to run smoother, even with GitLens enabled. I haven't tested on previous VSCodium versions so I don't know if the fix comes from the last version. Here is my Git output today :

```
[2022-05-10T10:20:02.333Z] > git rev-parse --show-toplevel [10ms]
[2022-05-10T10:20:02.387Z] > git rev-parse --git-dir --git-common-dir [48ms]
[2022-05-10T10:20:02.392Z] Open repository: /...
[2022-05-10T10:20:02.416Z] > git status -z -uall [19ms]
[2022-05-10T10:20:02.433Z] > git symbolic-ref --short HEAD [15ms]
[2022-05-10T10:20:02.451Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/67-champ-obligatoire refs/remotes/67-champ-obligatoire [16ms]
[2022-05-10T10:20:02.650Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [196ms]
[2022-05-10T10:20:02.651Z] > git remote --verbose [196ms]
[2022-05-10T10:20:02.777Z] > git config --get commit.template [66ms]
[2022-05-10T10:20:03.160Z] > git show --textconv :CHANGELOG.md [139ms]
[2022-05-10T10:20:03.178Z] > git ls-files --stage -- /.../CHANGELOG.md [155ms]
[2022-05-10T10:20:03.395Z] > git cat-file -s 3a74f319c452df8e99db2ca704ab30f463cd77ef [214ms]
[2022-05-10T10:20:03.402Z] > git check-ignore -v -z --stdin [12ms]
```

Some commands still take longer than 100ms on VSCodium startup, but none are afterward.

🎉

**Comment by eloo** [comment]
Can confirm with the new version it seems to be better

**Comment by vic-pic** [comment]
Hi all,
I have installed the 1.67.1 version and I can no longer get the git extension to work: appears to be installed and enabled, but when I open the git panel appears the following sentence:
`If you would like to use git features, please enable git in your settings`
and in settings there is no git setting to change.
If I disable the `Git (built-in)` extension and after a reload of vscodium, I enable it again it appears to work, but when I restart vscodium it stops working, showing the sentence above.

**Comment by enx1998** [comment]
Hi all,
I have installed the 1.67.1 version and I can no longer get the git extension to work: appears to be installed and enabled, but when I open the git panel appears the following sentence:
If you would like to use git features, please enable git in your settings
and in settings there is no git setting to change.
If I disable the Git (built-in) extension and after a reload of vscodium, I enable it again it appears to work, but when I restart vscodium it stops working, showing the sentence above.

**Comment by jeffery9** [comment]
git status is very slow.
```
[2022-08-04T08:34:58.625Z] > git cat-file -s 92cf8c1633f3687b4d266f001a36fbd7af6688a3 [45ms]
[2022-08-04T08:35:33.889Z] > git status -z -uall [84556ms]
[2022-08-04T08:35:33.932Z] > git symbolic-ref --short HEAD [20ms]
[2022-08-04T08:35:34.015Z] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/zll-test refs/remotes/zll-test [62ms]
[2022-08-04T08:35:34.074Z] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [37ms]
[2022-08-04T08:35:34.081Z] > git remote --verbose [22ms]
[2022-08-04T08:35:34.111Z] > git config --get commit.template [10ms]
[2022-08-04T08:36:01.072Z] > git rev-parse --show-toplevel [46ms]
```

vscode version
```
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
```

**Comment by MatthiasPortzel** [comment]
I upgraded from 1.66 to 1.70 today and Git performance is much better! This issue might be solved.
